### ISSUE TITLE
Can/should unencoded end-of-line characters appear inside a string?

### ISSUE THREAD

**Issue by billpg** [tlocke/zish#11]
Consider... {"MyMultilineString": "Hello
World!"}

If this should be allowed, code dealing with ZISH files will have to be careful to open files as binary to avoid the OS normalizing the end-of-line characters. (Consider a string that contains a mixture of CR and LF characters.)

Suggest requiring that all white-space characters in strings other than U+0020 (ASCII space) must be encoded using the back-slash encoding.

**Comment by gwicksted** [comment]
+1 if zish will be commonly used in static files committed to a repo via git (likely).

Sure, you could configure `.gitattributes` to have them listed as binary or with a specified line-ending but honestly this is a pain point with just about any "text" file especially with something like FTP or multiple platforms editing the file.

One less footgun without it.

**Comment by tlocke** [comment]
Currently, Zish takes the same approach as [Python source code](https://docs.python.org/3.6/reference/lexical_analysis.html#physical-lines) which is to say that since the text is Unicode, the Unicode EOL rules apply (ie. treat both LF and CR+LF as EOLs). My reasoning is that if it works for Python code, it should work for Zish :-)

**Comment by gwicksted** [comment]
Vote to close this issue as "won't fix"

**Comment by tlocke** [comment]
Agreed.
