### ISSUE TITLE
Comments from billpg on Hacker News

### ISSUE THREAD

**Issue by tlocke** [tlocke/zish#2]
Here's a wonderful [comment](https://news.ycombinator.com/item?id=15931567) from [billpg](https://news.ycombinator.com/user?id=billpg) on Hacker News. I need to think hard about all these things that he's raised.

> My unsolicited comments. I really want to see a good JSON-done-right out there and your spec is maybe 90% there.
> 
> I'd rather only /* */ comments were allowed. By allowing //, you've now got two varieties of white-space the parser needs to be aware of. Because of this, I can't take multiple lines of ZISH and join them together into a single line. (Something both JSON and XML can do.)
> 
> What is a "line"? CR, LF, CRLF, LFCR, FF, VT, U+0085, U+2028, U+2029?
> 
> Am I required to treat ZISH files as "binary"? Could I convert all of those end-of-line bytes into my OS's preferred form without losing data?
> 
> The notation of ending a line with a \ also prevents joining multiple lines into a single line. Maybe formalize "string"+"string" as an explicit string joining notation? (Or if not +, some other character to notate string concatenation.)
> 
> Given you have the decimal type, is float necessary? Values with a "e" are still expressed with decimal digits.
> 
> Is there a limit to numeric types? What if my ZISH file contained a several hundred 9s in a row?
> 
> Sets seems unnecessary given you already have lists. You can take a list and treat it as a set after parsing with no loss of data.
> 
> I very much like the addition of timestamps and binary without needing a string. This is my big pet peeve of JSON.
> 
> Your examples include uses of null and true, but your spec doesn't define those values. (Or false for that matter.)
> 
> The description of map doesn't specify if the order of keys is significant. Is {"a":"b", "c":"d"} the same as {"c":"d", "a":"b"} ?

**Comment by gwicksted** [comment]
@tlocke it would be great if these were individual tickets so discussions can take place regarding each - even if nothing more than documenting a response of why or why not.  Just link them back to this one to track overall progress as they're closed.

Also, I think zish needs a very clear goal to make choices like these easier to make.  The front page doesn't currently state what that goal is but I'll give it a shot:

I *think* the goal is pointing towards becoming JSON 2.0 by being incrementally better than its predecessor for the same subset of problems that JSON currently addresses.  It is not a superset nor a subset of the original so it is not backwards compatible (hence the 2.0).  This might be a tad dangerous since someone could mistake one for the other without being careful to check the file extension but I wouldn't bother prefixing each file with a "zish" or anything like that -- especially because it is not named "JSON version X"

A few questions of my own:

* How should times without dates (remind me every day at 9:00 AM to do X) be handled?  I don't think the RFC allows this.  Perhaps `T00:00:00` or use strings: `"00:00:00"` but then ambiguities could occur

* What are the min/max for dates?  RFC3339 isn't specific about that.

* How should dates without times (birthday, expiration date) be handled?  A relative-to-UTC time is usually not very helpful.  These are (rarely) correctly represented as an unknown local offset `2017-12-15T17:53:13.000-00:00` where `-00:00` or no offset is different than `+00:00` (which is analogous to `Z`).

* How should currency be handled?  It may not be part of the spec but guidance could be a win for everyone same regarding URLs, emails, and unit specifiers (grams, feet, joules, dollars)

* Why bother with `null` when omitting the member altogether implies a similar meaning?  Unless you're implying the boolean quantum bit is in a superposition, it might be best to disallow them altogether?

**Comment by billpg** [comment]
Hi there. I'm the same billpg that left the original comment on Hacker News.

I agree with @gwicksted , that it would be better to split off my suggestions as separate issues so they can be discussed in isolation, rather than taking all my comments as a package.

I personally would like to see this a "JSON done right". The big selling point for me was timestamps and binary rather than falling back to stringly typed values. Allowing comments as "only equivalent to whitespace" is a nice to have.

**Comment by billpg** [comment]
I've taken the initiative and raised separate issues myself, having just found out that I have the ability to do so.

**Comment by gwicksted** [comment]
Vote to close this issue as it has been broken up into several tickets.

**Comment by tlocke** [comment]
Agreed.
