### ISSUE TITLE
Allow long strings to be split on multiple lines with "abc"+"def".

### ISSUE THREAD

**Issue by billpg** [tlocke/zish#7]
Suggestion: Change the grammar such a single string is defined as...
(If you will forgive my I-don't-really-know-formal-grammar syntax.)

(partial string) = (quote) (characters)* (quote)
(string) = ( (partial string) (ws) "+" (ws) )* (partial string) 

<s>With similar rules for the byte-array type, allowing long strings of bytes to be split onto different lines.</s>

Require that UTF-8 multi-byte sequences can't be separated by the "plus" notation.
<s>Require that all but the last partial base64 block must be a complete 3-byte block, only allowing == padding on the last one.</s>

Edit: @gwickstead correctly points out there is no problem ignoring end-of-line control characters and spaces in base64, so I've removed those points, leaving this issue only as a suggestion to split *strings* on multiple lines.

**Comment by gwicksted** [comment]
The binary (base64) data should allow an arbitrary number of spaces and CR / LF since they're invalid base64 characters and are common in large base64 strings like certificates.

**Comment by gwicksted** [comment]
P.S. @billpg if you're interested in learning how to represent these a bit more "formally" (you communicated it quite clearly as-is) take a look at [bnf](https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form) and [ebnf](https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form) which are very close to what you have written above.

They aren't very complex to master once you've written a few simple languages.  My advice if you want to get your feet wet is to download [Gold Parser](http://www.goldparser.org/) which is a fully contained micro IDE with several example languages and succinct documentation.  It has a BNF-like grammar and an LALR parser generator that lets you test your grammar and even compile it to several back-end implementations with very little time investment.

Many compilers/interpreters are "recursive descent" which are fast and not bad to write once you've formalized the grammar but GOLD is great for prototyping and rapidly adapting your grammar as you try it out.

(the following are hand-typed and may contain errors especially since it's late)

Your example in BNF:

```bnf
<characters> ::= "a" | "b"  ; I'm not typing them all
<partial-string> ::= '"' <characters>* '"'
<string> ::= { <partial-string> <opt-whitespace> "+" <opt-whitespace> } * <partial-string>
; or
<string> ::= <partial-string> | <partial-string> <opt-whitespace> "+" <opt-whitespace> <string>
```

Your example in EBNF:

```ebnf
characters = "a" | "b" ; (* I'm not typing them all! *)
partial string = '"' , characters * , '"' ;
string = partial string , { [ ws ] , "+" , [ ws ] , partial string } ;
; or
string = partial string
       | partial string , [ ws ] , "+" [ ws ] , string ;
ws = ? white space characters ? ;
```

Super simplistic introduction to BNF:

* terminals can be though of as tokens like strings
* non-terminals are used to describe the syntax
* `::=` can be thought of as "is defined as" sort of like "="
* `|` is OR just like Regex
* `<name>` is a named symbol
* `words` are tokens (terminal strings) and _may_ be quoted or unquoted
* `[` ... `]` means optional
* `+` is 1-or-more like Regex
* `*` is 0-or-more like Regex
* `{` ... `}` is a group which is an AND operation just like if no parenthesis existed but it allows you to apply a multiplicity operator like `*` to the entire group
* `;` is the comment character

EBNF is similar and there are several variations.  Some differences are:

* Some allow spaces in symbol names so instead of `<this-is-a-symbol>` in BNF, you can write `<this is a symbol>` or `this is a symbol` in some implementations
* `=` used instead of `::=`
* `(*` ... `*)` is a multi-line comment and some disallow the use of `;` for comments
* `{` ... `}` is now a repetition indicator instead of a grouping
* `(` ... `)` is used for grouping
* `[` ... `]` means optional
* `;` means "termination" indicating the end of a symbol definition like in C/C++
* `'text'` and `"text"` mean the same thing and quotes are now required
* `,` is used to concatenate two things together like a terminal string and a non-terminal such as `"-", digits`
* `-` is used to subtract what is disallowed (an "exception" to the rule) such as `digits - '0'`
* `?` ... `?` is basically "insert special meaning here" such as pre-defined groups of characters

**Comment by gwicksted** [comment]
Voting to close as "won't fix"

This is currently supported by ending a line with the escape character followed immediately by the `EOL` marker which is defined as:

```g4
fragment
EOL
    : '\u000A' // LF: Line Feed
    | '\u000B' // VT: Vertical Tab
    | '\u000C' // FF: Form Feed
    | '\u000D' // CR: Carriage Return
    | '\u000D\u000A' // CR+LF: CR followed by LF
    | '\u0085' // NEL: Next Line
    | '\u2028' // LS: Line Separator
    | '\u2029' // PS: Paragraph Separator
    ;
```

The existing spec is not my personal preference for multi-line support but it works and having more than one option is even less preferable.

So for now I think the best option is to leave everything as-is.

**Comment by tlocke** [comment]
Okay, I'll leave it as it is.
