### ISSUE TITLE
Remove sets.

### ISSUE THREAD

**Issue by billpg** [tlocke/zish#8]
Given that ZISH already has the [ and ] notation for lists, allowing sets seems unnecessary. You can take a list and treat it as a set with no loss of data. It would also free up the round brackets for other uses, yet to be defined.

Response by "Flenser" on my original Hacker News comment:
"Sets could be reordered to improve compression. Not a big benefit but it would depend on your data."

**Comment by gwicksted** [comment]
The only advantage I see for sets is during deserialization where it may deserialize to an optimal data structure such as a `HashSet<T>` (C#) instead of a general purpose tree or list structure.

Whether this is worth the additional complexity is hard to say.  I can't think of any implementations that had built-in support to communicate this constraint off the top of my head (without requiring additional schema information).

**Comment by tlocke** [comment]
True, I've never felt the lack of a set type in JSON, and things can always be added in later if people clamour for it. I'll remove sets.

**Comment by gwicksted** [comment]
Vote to close this issue as Solved.

**Comment by tlocke** [comment]
Yes, I agree it's solved.
